import IERC20Abi from './IERC20.json';
import Multicall2Abi from './Multicall2.json';
import IAgniPoolAbi from './core/IAgniPool.json';
import INonfungiblePositionManagerAbi from './periphery/INonfungiblePositionManager.json';
import IQuoterV2Abi from './periphery/IQuoterV2.json';
import IStakingPoolAbi from './launchpad/IStakingPool.json';
import InsurancePoolAbi from './launchpad/IInsurancePool.json';
import IIdoPoolAbi from './launchpad/IIdoPool.json';
import GasLimitMulticallAbi from './GasLimitMulticall.json';
import RUSDYAbiJson from './RUSDY.json';
import WETHAbiJson from './WETH.json';
import ISwapRouterAbi from './periphery/ISwapRouter.json';
import AgniProjectPartyReward from './AgniProjectPartyReward.json';
export const IERC20 = IERC20Abi;
export const Multicall2 = Multicall2Abi;
export const IAgniPool = IAgniPoolAbi;
export const INonfungiblePositionManager = INonfungiblePositionManagerAbi;
export const IStakingPool = IStakingPoolAbi;
export const InsurancePool = InsurancePoolAbi;
export const IdoPool = IIdoPoolAbi;
export const IQuoterV2 = IQuoterV2Abi;
export const GasLimitMulticall = GasLimitMulticallAbi;
export const ISwapRouter = ISwapRouterAbi;
export const RUSDYAbi = RUSDYAbiJson;
export const WETHAbi = WETHAbiJson;
export const AgniProjectPartyRewardAbi = AgniProjectPartyReward;
